### PR TITLE
setting attributes of builtin types should fail

### LINKED ISSUE #1078: can set attributes of builtins in python 3
the algorithm to set an attribute of a builtin is broken in python 3. 

it checks the repr for the word `type`

but `class` is in the repr for python 3 which means I can do

```python
setattr(int, 'foo', 'bar')
```
without issue... 

Also `genericSetAttr` doesn't check for a builtin so it's fine to just do 
```python
int.foo = 'bar'
```

### PR DESCRIPTION
**Pull request by s-cork**
This pr aims to fix #1078 

The approach I took was to add the appropriate `tp$setattr` function to builtin type and type objects 

This negates the need to check whether an object is a builtin in the `builtin.setattr` function

### CODE REVIEW

File: src/import.js [hunk 1]
```diff
@@ -96,6 +96,9 @@ Sk.doOneTimeInitialization = function (canSuspend) {
         if ((func.prototype instanceof Sk.builtin.object ||
              func === Sk.builtin.object) && !func.sk$abstract) {
             setUpClass(func);
+            func.tp$setattr = function(obj, pyName, value) {
```
Comment (meredydd) [inline src/import.js:99]: Move this to `setUpClass()`?

Comment (meredydd) [reply src/import.js:99]: Also, that's the wrong call signature for `tp$setattr`!
```
tp$setattr = function(pyName, data, canSuspend)
```

File: src/type.js [hunk 2]
```diff
@@ -514,6 +514,9 @@ Sk.builtin.type["$r"] = function () {
         return new Sk.builtin.str("<type 'type'>");
     }
 };
+Sk.builtin.type.tp$setattr = function(obj, pyName, value) {
```
Comment (meredydd) [inline src/type.js:517]: Fix arg names/sig

File: src/type.js [hunk 3]
```diff
@@ -514,6 +514,9 @@ Sk.builtin.type["$r"] = function () {
...
+    throw new Sk.builtin.TypeError("can't set attributes of built-in/extension type '" + obj.tp$name + "'");
```
Comment (meredydd) [inline src/type.js:518]: We're pretty confident we know what `obj.tp$name` is here, right? `obj` will be `Sk.builtin.type`!

However, this three-line function is useful in several places, hence the copy-and-paste. Perhaps it should be abstracted out? (Minor thing)

File: src/import.js (hunk 1 above)
Comment (s-cork) [reply src/import.js]: moved and done

File: src/type.js (hunk 2 above)
Comment (s-cork) [reply src/type.js]: done

File: src/type.js (hunk 3 above)
Comment (s-cork) [reply src/type.js]: I've changed this to `this.tp$name`
This is currently correct but would need to adjust depending on how #1079  is resolved...

Comment (s-cork) [reply src/type.js]: I could change this to `this.prototype.tp$name`

**Comment by s-cork** [comment]
@meredydd changes made - i wasn't sure what to do about the error message - for now i've left it as `this.tp$name`.
