### PR TITLE
Unpack reverse before comparison for sorted()

### LINKED ISSUE #459: sort(reverse=False) acts as if it is sort(reverse=True)
Run the following code in Skulpt:

x = ['a', 'x', 'm']
x.sort()
print x
x.sort(reverse=True)
print x
x.sort(reverse=False)
print x

The output will be:

['a', 'm', 'x']
['x', 'm', 'a']
['x', 'm', 'a']

The first two are correct - the last one is incorrect.  I am guessing this is an easy fix.  :)

### PR DESCRIPTION
**Pull request by fsladkey**
Fixes #459.

The issue is that currently, calling sorted([2, 3, 1], reverse=False) returns [3, 2, 1] (same as sorted([2, 3, 1], reverse=True). This is my first time contributing, please let me know anything I can do to make this more correct. Thanks!

### CODE REVIEW

File: src/sorted.js [hunk 1]
```diff
@@ -4,6 +4,16 @@ Sk.builtin.sorted = function sorted (iterable, cmp, key, reverse) {
     var iter;
     var compare_func;
     var list;
+    var rev;
+
+    if (reverse === undefined) {
+        rev = false;
+    } else if (reverse === Sk.builtin.none.none$) {
```
Comment (waywaaard) [inline src/sorted.js]: This check is not sufficient as we can still pass a float etc. I think we need to check if the passed argument is an int/index. Bool is a subtype of int.

**Comment by albertjan** [comment]
I merged this manually addressing @waywaaard comments.
