### PR TITLE
fix: #931

### LINKED ISSUE #931: With new Skulpt,turtle register_shape() will raise error:wrapperFn() takes 0 positional arguments but 1 was  given
With this new version of Skulpt,the turtle register_shape() function will raise an error:`wrapperFn() takes 0 positional arguments but 1 was  given`.It is OK before the July version.The register_shape() invocation is as below:
`register_shape("football.png")`

### PR DESCRIPTION
**Pull request by viewerw**
fix #931

### CODE REVIEW

File: src/lib/turtle.js [hunk 1]
```diff
@@ -1321,7 +1321,8 @@ function generateTurtleModule(_target) {
             }
         };
         proto.$register_shape.minArgs = 1;
-
+        proto.$register_shape.co_varnames = ["name", "points"];
+
```
Comment (s-cork) [inline src/lib/turtle.js:1325]: looking at the definition in cpython - isn't the second argument called shape?

Comment (viewerw) [reply src/lib/turtle.js]: maxArgs is not necessary, the defaultValue of maxArgs is the func's length

**Review by s-cork — APPROVED** [review]
